### ISSUE TITLE
Scanopy constantly creates new host for daemon

### ISSUE THREAD

**Issue by Skylark13** [scanopy/scanopy#389]
**Describe the bug**
I started a daemon on a separate machine than the Scanopy server to get the docker services from that host, and the daemon seems to be registered properly on the Daemons page of the server, but on the Hosts page, a new host with the daemon name gets added repeatedly.

Note the ideal solution would be to not require a separate daemon running on another host, if / when #321 gets done.

**To Reproduce**
1. Added a daemon in the Daemons page of Scanopy server
2. Added that daemon to my other host through Portainer using the docker-compose (only edited the SCANOPY_SERVER_URL variable to point to the server's IP)
3. Noticed that new hosts were being added all the time.

You will see in the daemon logs, after the registration request there is a message:

```
Error: Registration failed: HTTP 500 Internal Server Error
```

I think this must be the cause for the problem - the daemon gets registered but the acknowledgement of the registration from the server never gets registered properly on the daemon, so it just sends another registration request later. Ad infinitum. But I don't know what is causing this HTTP 500 error.

**Expected behavior**
The daemon would add one host to the server (which I would then merge with another existing host).

**Screenshots**
Daemons:

<img width="1003" height="620" alt="Image" src="https://github.com/user-attachments/assets/b41c56e9-1b28-4abe-bc75-493e0620e5c8" />

Hosts (there are 37 named babylon5-daemon at the point when I stopped the daemon):

<img width="1470" height="1166" alt="Image" src="https://github.com/user-attachments/assets/4bffff8c-9d19-483c-9928-2e6d5466e271" />

**Environment:** 
 - Scanopy server & daemon version (can be found in logs) 🚀 Scanopy Server v0.12.7
 - Host: Proxmox on host, LXC container running Docker, Scanopy installed using Docker-compose
 - OS: Proxmox
 - Browser Firefox

**Additional context**
Server log contains this line every minute:
```
2025-12-29T19:54:58.464840Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 78379160-4e6f-4e21-b20b-a18e2ca3cb3d, network_id: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9, name: "babylon5-daemon", url: "http://10.0.1.5", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
```

Daemon log:
```
2025-12-29T19:45:45.664572Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:45:45.664972Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:45:45.665296Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:45:45.665308Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:45:45.665316Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:45:45.665321Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:45:45.665353Z  INFO daemon: API key available: [redacted]
2025-12-29T19:45:45.666876Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:45:45.666910Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:46:46.990419Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:46:46.990834Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:46:46.991210Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:46:46.991224Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:46:46.991232Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:46:46.991239Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:46:46.991252Z  INFO daemon: API key available: [redacted]
2025-12-29T19:46:46.992557Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:46:46.992589Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:47:49.692127Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:47:49.692531Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:47:49.692849Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:47:49.692860Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:47:49.692866Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:47:49.692872Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:47:49.692883Z  INFO daemon: API key available: [redacted]
2025-12-29T19:47:49.694328Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:47:49.694361Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
2025-12-29T19:48:50.590354Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:48:50.590697Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:48:50.591109Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:48:50.591122Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:48:50.591130Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:48:50.591136Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:48:50.591148Z  INFO daemon: API key available: [redacted]
2025-12-29T19:48:50.592442Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:48:50.592474Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:49:51.822243Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:49:51.822680Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:49:51.823104Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:49:51.823198Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:49:51.823205Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:49:51.823209Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:49:51.823220Z  INFO daemon: API key available: [redacted]
2025-12-29T19:49:51.824549Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:49:51.824567Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:50:52.920567Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:50:52.920930Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:50:52.921270Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:50:52.921282Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:50:52.921289Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:50:52.921295Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:50:52.921308Z  INFO daemon: API key available: [redacted]
2025-12-29T19:50:52.922769Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:50:52.922805Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:51:53.783544Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:51:53.783748Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:51:53.783964Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:51:53.783972Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:51:53.784029Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:51:53.784062Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:51:53.784087Z  INFO daemon: API key available: [redacted]
2025-12-29T19:51:53.785097Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:51:53.785117Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:52:55.148988Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:52:55.149589Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:52:55.149895Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:52:55.149905Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:52:55.149911Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:52:55.149916Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:52:55.149926Z  INFO daemon: API key available: [redacted]
2025-12-29T19:52:55.151274Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:52:55.151303Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:53:57.030461Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:53:57.030988Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:53:57.032055Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:53:57.032084Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:53:57.032096Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:53:57.032103Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:53:57.032119Z  INFO daemon: API key available: [redacted]
2025-12-29T19:53:57.033989Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:53:57.034023Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
2025-12-29T19:54:58.458590Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T19:54:58.458975Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T19:54:58.459362Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T19:54:58.459375Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T19:54:58.459383Z  INFO daemon: 🔗 Server at http://10.0.1.2:60072
2025-12-29T19:54:58.459390Z  INFO daemon: Network ID available: 2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9
2025-12-29T19:54:58.459423Z  INFO daemon: API key available: [redacted]
2025-12-29T19:54:58.460789Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d network_id=2b29e9ee-e24f-4319-8f1b-f4eef2c5d9a9 has_docker=true
2025-12-29T19:54:58.460825Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=78379160-4e6f-4e21-b20b-a18e2ca3cb3d
Error: Registration failed: HTTP 500 Internal Server Error
```

**Before submitting**
[x] I have reviewed [The docs](https://scanopy.net/docs)

**Comment by Matthi-17** [comment]
Hi,

I have the same situation.

My Environment is:

- Scanopy running in a Ubuntu 24.04 VM with Docker on Proxmox
- Scanopy daemon on a raspberry pi with Docker Compose
- Browser Safari
- also using portioner on both docker hosts

Is a new installation from now.

**Comment by mayanayza** [comment]
Can you both share debug logs from the daemon + server? Please run both with SCANOPY_LOG_LEVEL=debug and try registering the daemon.

**Comment by Matthi-17** [comment]
Hi mayanayza,


I hope this can help  :)

In the meantime I added Traefik as a reverse proxy, so it is https with domain name and port 443. 

Logfile daemon:

2025-12-29T21:17:03.568228Z  INFO daemon: 🤖 Scanopy Daemon v0.12.7
2025-12-29T21:17:03.568955Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-29T21:17:03.569651Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-29T21:17:03.569673Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-29T21:17:03.569687Z  INFO daemon: 🔗 Server at https://scanopy.domain.com.     **#changed**
2025-12-29T21:17:03.569698Z  INFO daemon: Network ID available: 33584ae1-d36a-47fa-a55e-b5414efa07a4
2025-12-29T21:17:03.569710Z  INFO daemon: API key available: [redacted]
2025-12-29T21:17:03.576436Z DEBUG scanopy::daemon::utils::base: Connecting to Docker
2025-12-29T21:17:03.577952Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b network_id=33584ae1-d36a-47fa-a55e-b5414efa07a4 has_docker=true
2025-12-29T21:17:03.578256Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
Error: Registration failed: HTTP 500 Internal Server Error

Logfile Server:

2025-12-29T21:10:41.226052Z  INFO scanopy::server::logging::subscriber: { id: 43ab4551-3e9d-4d89-a295-1b877a31a9d5, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:10:41.225925401 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-29T21:10:41.382240Z  INFO scanopy::server::logging::subscriber: { id: 30f5abd3-cc66-4b52-9b9b-9218764a72c4, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:10:41.382113442 UTC, metadata: {"trigger_stale":false}, authentication: User { user_id: 9a44275e-566d-4356-97ed-9b3927b05032, permissions: Owner } }
2025-12-29T21:10:41.398896Z  INFO scanopy::server::logging::subscriber: { id: a7c42bd5-d105-4c49-aa54-42203d0b2714, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:10:41.398759560 UTC, metadata: {"trigger_stale":false}, authentication: User { user_id: 9a44275e-566d-4356-97ed-9b3927b05032, permissions: Owner } }
2025-12-29T21:10:41.451026Z  INFO scanopy::server::logging::subscriber: { id: 471b7677-7e64-4b93-9915-103f77797625, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:10:41.450907718 UTC, metadata: {"trigger_stale":false}, authentication: User { user_id: 9a44275e-566d-4356-97ed-9b3927b05032, permissions: Owner } }
2025-12-29T21:10:41.458896Z  INFO scanopy::server::logging::subscriber: { id: 661acf56-55dc-4249-bff7-e621b3bf02af, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:10:41.458760496 UTC, metadata: {"trigger_stale":false}, authentication: User { user_id: 9a44275e-566d-4356-97ed-9b3927b05032, permissions: Owner } }
2025-12-29T21:11:41.639765Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 67861b3a-90e4-4f18-acef-661e7fd1ec6b, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, name: "dockerb", url: "http://192.168.xxx.xxx:60073", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
2025-12-29T21:11:41.676117Z  INFO scanopy::server::logging::subscriber: { id: ce49f886-1e20-4bed-9539-4c70e67029fd, entity_type: Host, entity_id: 90223f39-ae28-4db8-aec8-9f650f36c35d, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: created, timestamp: 2025-12-29 21:11:41.676104267 UTC, metadata: {"trigger_stale":true}, authentication: Daemon }
2025-12-29T21:11:41.676152Z  INFO scanopy::server::hosts::service: Created host with children host_id=90223f39-ae28-4db8-aec8-9f650f36c35d host_name=dockerb interface_count=0 port_count=0 service_count=0
2025-12-29T21:11:41.795036Z  INFO scanopy::server::logging::subscriber: { id: 28a436a0-16c3-4474-9017-c46bbb2e0c8a, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:11:41.794905927 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-29T21:11:41.821545Z  INFO scanopy::server::logging::subscriber: { id: 775a2e58-bb09-4e22-b7f1-f4a3eca6ca7a, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:11:41.821401214 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-29T21:12:42.144913Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 67861b3a-90e4-4f18-acef-661e7fd1ec6b, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, name: "dockerb", url: "http://192.168.xxx.xxx:60073", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
2025-12-29T21:12:42.148368Z  INFO scanopy::server::logging::subscriber: { id: 19bd0db3-a410-41f6-a94b-488ffe07c2e6, entity_type: Host, entity_id: cdb077c1-567d-45f4-a2bd-d75866960ff9, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: created, timestamp: 2025-12-29 21:12:42.148356330 UTC, metadata: {"trigger_stale":true}, authentication: Daemon }
2025-12-29T21:12:42.148400Z  INFO scanopy::server::hosts::service: Created host with children host_id=cdb077c1-567d-45f4-a2bd-d75866960ff9 host_name=dockerb interface_count=0 port_count=0 service_count=0
2025-12-29T21:12:42.194767Z  INFO scanopy::server::logging::subscriber: { id: 0af8b09f-927a-4065-9197-d4b31f5a0253, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:12:42.194634236 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-29T21:12:42.221711Z  INFO scanopy::server::logging::subscriber: { id: efeae457-597d-499e-ba75-063761ff4a6f, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-29 21:12:42.221575608 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-29T21:13:42.634590Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 67861b3a-90e4-4f18-acef-661e7fd1ec6b, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, name: "dockerb", url: "http://192.168.xxx.xxx:60073", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
2025-12-29T21:13:42.670207Z  INFO scanopy::server::logging::subscriber: { id: 82f8beae-dd9a-4e4e-a151-3a4b72c9a6bb, entity_type: Host, entity_id: 4b197983-8d9b-4209-a9ad-ce53be8a342f, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: created, timestamp: 2025-12-29 21:13:42.670198420 UTC, metadata: {"trigger_stale":true}, authentication: Daemon }

**Comment by mayanayza** [comment]
can you run with SCANOPY_LOG_LEVEL=debug for the server too? Looks like those are info-level, but the logs I need to properly investigate are debug-level

**Comment by Matthi-17** [comment]
Hi mayanayza,

Sorry, I missed something on the server earlier. It should be debug.

`2025-12-30T06:57:31.415801Z  INFO scanopy::server::shared::events::bus: Registered event subscriber subscriber=topology_stale debounce_ms=200
2025-12-30T06:57:31.415821Z  INFO scanopy::server::shared::events::bus: Registered event subscriber subscriber=logging debounce_ms=0
2025-12-30T06:57:31.415826Z  INFO scanopy::server::shared::events::bus: Registered event subscriber subscriber=organization_onboarding debounce_ms=0
2025-12-30T06:57:31.416956Z DEBUG scanopy::server::auth::service: Cleaned up old login attempts
2025-12-30T06:57:31.447923Z  INFO server: 🚀 Scanopy Server v0.12.7
2025-12-30T06:57:31.447942Z  INFO server: 📊 Web UI: http://<your-ip>:60072
2025-12-30T06:57:31.447945Z  INFO server: 🔧 API: http://<your-ip>:60072/api
2025-12-30T06:57:31.452554Z DEBUG scanopy::server::discovery::service: Scheduled discovery 1122793e-4864-4f1d-8a82-ed155ea7b358 with cron: 0 0 0 * * *
2025-12-30T06:57:31.452672Z DEBUG scanopy::server::discovery::service: Scheduled discovery b8bd2682-c483-4f83-9797-ddc749f4d464 with cron: 0 0 0 * * *
2025-12-30T06:57:31.452790Z DEBUG scanopy::server::discovery::service: Scheduled discovery ce96acd2-0ae8-4a43-8f2c-5d5a3f17b372 with cron: 0 0 0 * * *
2025-12-30T06:57:31.452876Z DEBUG scanopy::server::discovery::service: Scheduled discovery bf1f5f21-9370-4f46-8ab1-2086797df80b with cron: 0 0 0 * * *
2025-12-30T06:57:31.452933Z  INFO scanopy::server::discovery::service: Discovery scheduler started with 4 jobs
2025-12-30T06:57:41.450783Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:57:41.452242Z DEBUG scanopy::server::auth::middleware::rate_limit: Rate limiter cleanup: user keys=0, anonymous keys=1
2025-12-30T06:57:51.518356Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:57:55.661708Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=45 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T06:58:01.576775Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:11.631235Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:21.714120Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:25.627710Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=16 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T06:58:31.776839Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:38.971638Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 67861b3a-90e4-4f18-acef-661e7fd1ec6b, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, name: "dockerb", url: "http://192.168.111.32:60073", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
2025-12-30T06:58:38.989100Z  INFO scanopy::server::logging::subscriber: { id: f3e4fd47-8fd0-49c3-a451-8b8a1f37bd40, entity_type: Host, entity_id: 8c00f893-5252-4bf3-bacd-6d7e3d8d3103, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: created, timestamp: 2025-12-30 06:58:38.989088440 UTC, metadata: {"trigger_stale":true}, authentication: Daemon }
2025-12-30T06:58:38.989143Z  INFO scanopy::server::hosts::service: Created host with children host_id=8c00f893-5252-4bf3-bacd-6d7e3d8d3103 host_name=dockerb interface_count=0 port_count=0 service_count=0
2025-12-30T06:58:38.990073Z DEBUG request_log: request completed method=POST path=/api/daemons/register status=500 duration_ms=22 ip=172.20.0.2 entity_type="daemon" entity_id="67861b3a-90e4-4f18-acef-661e7fd1ec6b"
2025-12-30T06:58:39.096947Z  INFO scanopy::server::logging::subscriber: { id: e340d437-60ba-4aa5-91f1-a6d0fd983ee0, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-30 06:58:39.096587661 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-30T06:58:39.097066Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:58:39.097265Z DEBUG scanopy::server::shared::events::bus: Event batch processed subscriber=topology_stale batch_size=1 org_count=1 events_per_org={None: 1} duration_ms=79 success=true
2025-12-30T06:58:39.168015Z  INFO scanopy::server::logging::subscriber: { id: 4d769622-6918-444c-8f5a-938d9c078cff, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-30 06:58:39.167436566 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-30T06:58:39.168123Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:58:39.223935Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:58:39.224080Z DEBUG scanopy::server::shared::events::bus: Event batch processed subscriber=topology_stale batch_size=1 org_count=1 events_per_org={None: 1} duration_ms=6 success=true
2025-12-30T06:58:39.230350Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:58:41.452716Z DEBUG scanopy::server::auth::middleware::rate_limit: Rate limiter cleanup: user keys=0, anonymous keys=0
2025-12-30T06:58:41.830844Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:51.887997Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:58:55.621700Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=10 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T06:59:01.945624Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:11.999536Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:22.093927Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:25.617050Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=5 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T06:59:32.153242Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:39.754182Z  INFO scanopy::server::daemons::handlers: DaemonRegistrationRequest { daemon_id: 67861b3a-90e4-4f18-acef-661e7fd1ec6b, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, name: "dockerb", url: "http://192.168.xxx.xxx:60073", mode: Push, capabilities: DaemonCapabilities { has_docker_socket: true, interfaced_subnet_ids: [] } }
2025-12-30T06:59:39.762043Z  INFO scanopy::server::logging::subscriber: { id: a40c72c8-18c4-4e8e-82bd-4bd6e9c500d8, entity_type: Host, entity_id: 2850ef7b-9ca7-4e97-afaf-92bd40c0ae4a, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: created, timestamp: 2025-12-30 06:59:39.762033769 UTC, metadata: {"trigger_stale":true}, authentication: Daemon }
2025-12-30T06:59:39.762077Z  INFO scanopy::server::hosts::service: Created host with children host_id=2850ef7b-9ca7-4e97-afaf-92bd40c0ae4a host_name=dockerb interface_count=0 port_count=0 service_count=0
2025-12-30T06:59:39.762755Z DEBUG request_log: request completed method=POST path=/api/daemons/register status=500 duration_ms=12 ip=172.20.0.2 entity_type="daemon" entity_id="67861b3a-90e4-4f18-acef-661e7fd1ec6b"
2025-12-30T06:59:39.884515Z  INFO scanopy::server::logging::subscriber: { id: a4f3629a-4669-4b0b-9c35-9517345016cb, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-30 06:59:39.884132901 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-30T06:59:39.884631Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:59:39.884819Z DEBUG scanopy::server::shared::events::bus: Event batch processed subscriber=topology_stale batch_size=1 org_count=1 events_per_org={None: 1} duration_ms=67 success=true
2025-12-30T06:59:39.947748Z  INFO scanopy::server::logging::subscriber: { id: d86a0978-de4b-4dd3-9822-da56d6b96ead, entity_type: Topology, entity_id: 86e18110-9515-43cd-a7ef-0c6e2694e161, network_id: 33584ae1-d36a-47fa-a55e-b5414efa07a4, organization_id: None, operation: updated, timestamp: 2025-12-30 06:59:39.947357604 UTC, metadata: {"trigger_stale":false}, authentication: System }
2025-12-30T06:59:39.947854Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:59:40.019948Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:59:40.020085Z DEBUG scanopy::server::shared::events::bus: Event batch processed subscriber=topology_stale batch_size=1 org_count=1 events_per_org={None: 1} duration_ms=2 success=true
2025-12-30T06:59:40.022438Z DEBUG scanopy::server::topology::service::subscriber: Staleness notification skipped (no receivers): channel closed
2025-12-30T06:59:41.452705Z DEBUG scanopy::server::auth::middleware::rate_limit: Rate limiter cleanup: user keys=0, anonymous keys=0
2025-12-30T06:59:42.210595Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:52.267043Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T06:59:55.627859Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=16 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T07:00:02.341980Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T07:00:12.396715Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T07:00:22.479125Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"
2025-12-30T07:00:25.616249Z DEBUG request_log: request completed method=POST path=/api/daemons/{id}/heartbeat status=200 duration_ms=5 ip=172.20.0.1 entity_type="daemon" entity_id="7c447e04-6d74-4877-bd34-9a84b4c8c8a0"
2025-12-30T07:00:32.537667Z DEBUG request_log: request completed method=GET path=/api/health status=200 duration_ms=0 ip=127.0.0.1 entity_type="anonymous"`

**Comment by mayanayza** [comment]
Ok this is helpful! I have the root cause and will have a fix out shortly.

**Comment by Matthi-17** [comment]
When you have a Beta Docker Tag, I can test it.

**Comment by mayanayza** [comment]
This should be fixed in pre-release v0.12.8 - please give it a shot with that specific tag (it isn't pushed to latest yet).

**Comment by Matthi-17** [comment]
With this Tag the daemon is online. 

Logs from daemon:

`2025-12-30T17:34:53.642400Z  INFO daemon: 🤖 Scanopy Daemon v0.12.8
2025-12-30T17:34:53.642953Z  INFO scanopy::daemon::shared::config: Loaded daemon runtime state from /root/.config/daemon/config.json
2025-12-30T17:34:53.643718Z  INFO daemon: 🌐 Listening on: 0.0.0.0:60073
2025-12-30T17:34:53.643746Z  INFO daemon: 📁 Config file: "/root/.config/daemon/config.json"
2025-12-30T17:34:53.643759Z  INFO daemon: 🔗 Server at https://scanopy.domain.com #changed
2025-12-30T17:34:53.643770Z  INFO daemon: Network ID available: 33584ae1-d36a-47fa-a55e-b5414efa07a4
2025-12-30T17:34:53.643783Z  INFO daemon: API key available: [redacted]
2025-12-30T17:34:53.648587Z DEBUG scanopy::daemon::utils::base: Connecting to Docker
2025-12-30T17:34:53.650273Z  INFO scanopy::daemon::runtime::service: Registering with server daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b network_id=33584ae1-d36a-47fa-a55e-b5414efa07a4 has_docker=true
2025-12-30T17:34:53.650569Z  INFO scanopy::daemon::runtime::service: Sending register request daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:34:53.681718Z  INFO scanopy::daemon::runtime::service: Successfully registered with server, assigned ID: 67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:34:53.681763Z  INFO scanopy::daemon::runtime::service: Daemon fully initialized daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b network_id=33584ae1-d36a-47fa-a55e-b5414efa07a4 has_docker=true
2025-12-30T17:34:53.681784Z  INFO daemon: Daemon running in Push mode
2025-12-30T17:34:53.690588Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:35:23.696612Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:35:23.790071Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:35:53.693554Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:35:53.934670Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:36:23.691292Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:36:31.253826Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:36:53.693177Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:37:01.454304Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:37:23.696540Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:37:31.560664Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:37:53.693056Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:38:01.677550Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:38:23.693620Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:38:31.770402Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:38:53.693570Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:39:01.909813Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:39:23.691868Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:39:32.006791Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:39:53.723858Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:40:02.102047Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:40:23.698884Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:40:32.204669Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:40:53.690077Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:41:02.340256Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:41:23.725328Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:41:32.443571Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:41:53.723880Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:42:02.574564Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:42:23.694061Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:42:32.680393Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:42:53.693955Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:43:02.827081Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:43:23.693555Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:43:32.939534Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:43:53.694946Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:44:03.067808Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:44:23.694524Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:44:33.182087Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:44:53.693698Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b
2025-12-30T17:45:03.318277Z  INFO scanopy::daemon::shared::handlers: Received healthcheck request
2025-12-30T17:45:23.701926Z  INFO scanopy::daemon::runtime::service: Heartbeat sent daemon_id=67861b3a-90e4-4f18-acef-661e7fd1ec6b`

For now I am waiting for finished the first network scan from this daemon, now pending for 5 minutes. 

I'll you know!

**Comment by mayanayza** [comment]
Awesome! Given a new host is no longer constantly being created, I'm going to close this issue, please open a new one if anything else arises!

**Comment by Skylark13** [comment]
Thanks a lot for the quick turnaround, and thanks for providing the logs @Matthi-17 since I was busy with the holidays!

(to be clear to future readers, the server needed to be v0.12,8 too - not sure if the daemon had to as well, but just updating the daemon image returning the HTTP 500 error to v0.12.8 didn't fix it, but updating the server did)
